/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccountInfo.java
 *
 * Created on Sep 2, 2011, 9:52:59 AM
 */
package my.ccaregui;

/**
 *
 * @author Expresso BRM
 */
import java.sql.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JDialog;
public class AccountInfo extends javax.swing.JFrame {
    ConnectDB cnn = new ConnectDB();
    Connection con =  cnn.getConnection();
    /** Creates new form AccountInfo */
    public AccountInfo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMDN = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        lblDataVolume = new javax.swing.JLabel();
        lblExpiringDate = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDashBonus = new javax.swing.JLabel();
        lblMainBonus = new javax.swing.JLabel();
        lblCreditBalance = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EXPRESSO TELECOM GH");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACCOUNT RESOURCE INFORMATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Account Number");

        txtMDN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMDN.setForeground(new java.awt.Color(102, 0, 102));

        btnFind.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        lblDataVolume.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDataVolume.setForeground(new java.awt.Color(0, 0, 153));
        lblDataVolume.setText("Data Volume");

        lblExpiringDate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblExpiringDate.setForeground(new java.awt.Color(0, 0, 153));
        lblExpiringDate.setText("Expiring Date");

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Volume left (Mb)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Expiring Date");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 0));
        jLabel5.setText("Dash Bonus");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 0));
        jLabel6.setText("Main Bonus");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 0));
        jLabel7.setText("Credit Balance");

        lblDashBonus.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDashBonus.setForeground(new java.awt.Color(153, 0, 51));
        lblDashBonus.setText("Dash Bonus");

        lblMainBonus.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMainBonus.setForeground(new java.awt.Color(153, 0, 51));
        lblMainBonus.setText("Main Bonus");

        lblCreditBalance.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblCreditBalance.setForeground(new java.awt.Color(153, 0, 51));
        lblCreditBalance.setText("Credit Balance");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose)
                        .addGap(187, 187, 187))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtMDN, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblExpiringDate, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCreditBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMainBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDashBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCreditBalance, lblDashBonus, lblDataVolume, lblExpiringDate, lblMainBonus});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpiringDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreditBalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMainBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDashBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        
        if (con==null){
          ConnectDB cnn = new ConnectDB();
          Connection con =  cnn.getConnection();
          
         }   
        
       try
        {  
         
         DecimalFormat df = new DecimalFormat("##.00"); //new DecimalFormat("#.###");
         //SimpleDateFormat datef = new SimpleDateFormat("dd-MM-yyyy");
         if (txtMDN.getText().length()>=10){
          
            //Clear text box
            lblDataVolume.setText("Data Volume");
            lblExpiringDate.setText("Expiring Date");
            lblCreditBalance.setText("Credit Balance");
            lblMainBonus.setText("Main Bonus");
            lblDashBonus.setText("Dash Bonus");
            
            txtMDN.setText(txtMDN.getText().trim());
            String userInput ="233" +  txtMDN.getText().substring(txtMDN.getText().length()-9);
            txtMDN.setText(userInput);
            String myInput = txtMDN.getText().trim();

            //Data volume display;
            Statement s = con.createStatement();
            String select = "select current_bal, unixdate(valid_to), next_bal from bal_grp_sub_bals_t " +
                  " where obj_id0 in (select bal_grp_obj_id0 from service_t  where poid_id0 in " +
                  " (select obj_id0 from service_alias_list_t where name ='" + myInput + "')) " +
                  " and  to_date(unixdate_time(valid_to), 'dd-MON-YYYY HH24:MI:SS') >sysdate and rec_id2 in ('1000009')";

            ResultSet rows;
            rows = s.executeQuery(select);


                int cnt=0;
                double vlTotal = 0.0;
                while (rows.next()) {
                    cnt++; 

                   vlTotal =vlTotal + Double.valueOf(rows.getString(1))* -1;
                   lblDataVolume.setText(String.valueOf(df.format(vlTotal)));
                   lblExpiringDate.setText(String.valueOf(rows.getString(2)));

                }

               s.close();
               rows.close();


            //Main Balance
            Statement y = con.createStatement();
            select = "select current_bal from bal_grp_sub_bals_t " +
            " where obj_id0 in (Select Bal_Grp_Obj_Id0 From Service_T  Where Poid_Id0 In " +
            " (Select Obj_Id0 From Service_Alias_List_T Where Name ='" + myInput + "'))" +
            " and valid_to=0 and rec_id2 in ('288')"; 



            ResultSet rows1;
            rows1 = y.executeQuery(select);


                int cnt1=0;
                double vlMain = 0.0;
                while (rows1.next()) {
                    cnt1++; 

                   vlMain =vlMain + Double.valueOf(rows1.getString(1))* -1;
                   lblCreditBalance.setText(String.valueOf(df.format(vlMain)));
                //lblExpiringDate.setText(String.valueOf(rows.getString(2)));

                }



               y.close();
               rows1.close();


            //Main Bonus
            Statement z = con.createStatement();
            select = "select current_bal, unixdate(valid_to) from bal_grp_sub_bals_t " +
            " where obj_id0 in (Select Bal_Grp_Obj_Id0 From Service_T  Where Poid_Id0 In " +
            " (Select Obj_Id0 From Service_Alias_List_T Where Name ='" + myInput + "'))" +
            " and valid_to <> 0 and rec_id2 in ('1000036')and current_bal <>0 "; 



            ResultSet rows2;
            rows2 = z.executeQuery(select);


                int cnt2=0;
                double vlMainBonus = 0.0;

                while (rows2.next()) {
                    cnt2++; 

                   vlMainBonus =vlMainBonus + Double.valueOf(rows2.getString(1))* -1;
                   lblMainBonus.setText(String.valueOf(df.format(vlMainBonus)) + " - Valid till " +  String.valueOf(rows2.getString(2)));
                   //lblExpiringDate.setText(String.valueOf(rows.getString(2)));

                }

               z.close();
               rows2.close();


            //Dash Bonus
            Statement t = con.createStatement();
            select = "select current_bal from bal_grp_sub_bals_t " +
            " where obj_id0 in (Select Bal_Grp_Obj_Id0 From Service_T  Where Poid_Id0 In " +
            " (Select Obj_Id0 From Service_Alias_List_T Where Name ='" + myInput + "'))" +
            " and valid_to = 0 and rec_id='52' and rec_id2 in ('1000036')"; 



            ResultSet rows3;
            rows3 = t.executeQuery(select);


                int cnt3=0;
                double vlDashBonus = 0.0;
                while (rows3.next()) {
                cnt3++; 

                   vlDashBonus =vlDashBonus + Double.valueOf(rows3.getString(1))* -1;
                   lblDashBonus.setText(String.valueOf(df.format(vlDashBonus)));
                   //lblExpiringDate.setText(String.valueOf(rows.getString(2)));

                }

               t.close();
               rows3.close();


             if (cnt3<1 && cnt2<1 && cnt1<1 && cnt <1){
                   JOptionPane.showMessageDialog(null, "Record not found");              
             }
           }
         else{
             JOptionPane.showMessageDialog(null, "Enter Account Number");
             txtMDN.requestFocus();
         }
        
        }
       
        catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
       
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
         try{
           
           txtMDN.setText("");
           lblDataVolume.setText("Data Volume");
           lblExpiringDate.setText("Expiring Date");
           lblMainBonus.setText("Main Bonus");
           lblCreditBalance.setText("Credit Balance");
           lblDashBonus.setText("Dash Bonus");
           txtMDN.requestFocus();
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
         try{
             con.close();
             cnn=null;
             setVisible(false);
             dispose();
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try{
           con.close();
           cnn=null;
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try{
          setLocationRelativeTo(null);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AccountInfo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCreditBalance;
    private javax.swing.JLabel lblDashBonus;
    private javax.swing.JLabel lblDataVolume;
    private javax.swing.JLabel lblExpiringDate;
    private javax.swing.JLabel lblMainBonus;
    private javax.swing.JTextField txtMDN;
    // End of variables declaration//GEN-END:variables
}
