/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMenu.java
 *
 * Created on Jul 25, 2011, 3:10:25 PM
 */
package my.ccaregui;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JDialog;

/**
 *
 * @author Expresso BRM
 */
public class MainMenu extends javax.swing.JFrame {
   
    public static String mnUserID = Login.glbUserID;
    public static String mnUserName = Login.glbUserName;
    /** Creates new form MainMenu */
    
    public MainMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuDashEnq = new javax.swing.JMenu();
        mnuVCInfo = new javax.swing.JMenuItem();
        mnuDashEnquiries = new javax.swing.JMenuItem();
        mnuEVDOInfo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuBlackList = new javax.swing.JMenuItem();
        mnuESNCleanUp = new javax.swing.JMenuItem();
        mnuRUIMCleanUp = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        mnuActivations = new javax.swing.JMenu();
        mnuVoucherActivation = new javax.swing.JMenuItem();
        mnuMainReport = new javax.swing.JMenu();
        mnuRepVoucherActivated = new javax.swing.JMenuItem();
        mnuSetup = new javax.swing.JMenu();
        mnuSetupDealers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EXPRESSO TELECOM GH ver 1.2.1");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mnuDashEnq.setText("File");
        mnuDashEnq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDashEnqActionPerformed(evt);
            }
        });

        mnuVCInfo.setText("Voucher Info");
        mnuVCInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVCInfoActionPerformed(evt);
            }
        });
        mnuDashEnq.add(mnuVCInfo);

        mnuDashEnquiries.setText("Dash Enquiries");
        mnuDashEnquiries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDashEnquiriesActionPerformed(evt);
            }
        });
        mnuDashEnq.add(mnuDashEnquiries);

        mnuEVDOInfo.setText("Account  Info");
        mnuEVDOInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEVDOInfoActionPerformed(evt);
            }
        });
        mnuDashEnq.add(mnuEVDOInfo);
        mnuDashEnq.add(jSeparator1);

        mnuBlackList.setText("Black List");
        mnuBlackList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBlackListActionPerformed(evt);
            }
        });
        mnuDashEnq.add(mnuBlackList);

        mnuESNCleanUp.setText("ESN Clean up");
        mnuESNCleanUp.setEnabled(false);
        mnuESNCleanUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuESNCleanUpActionPerformed(evt);
            }
        });
        mnuDashEnq.add(mnuESNCleanUp);

        mnuRUIMCleanUp.setText("RUIM Clean up & PUK");
        mnuRUIMCleanUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRUIMCleanUpActionPerformed(evt);
            }
        });
        mnuDashEnq.add(mnuRUIMCleanUp);
        mnuDashEnq.add(jSeparator2);

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuDashEnq.add(mnuExit);

        jMenuBar1.add(mnuDashEnq);

        mnuActivations.setText("Activations");
        mnuActivations.setEnabled(false);

        mnuVoucherActivation.setText("Voucher");
        mnuVoucherActivation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVoucherActivationActionPerformed(evt);
            }
        });
        mnuActivations.add(mnuVoucherActivation);

        jMenuBar1.add(mnuActivations);

        mnuMainReport.setText("Report");
        mnuMainReport.setEnabled(false);
        mnuMainReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMainReportActionPerformed(evt);
            }
        });

        mnuRepVoucherActivated.setText("Vouchers Activated");
        mnuRepVoucherActivated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepVoucherActivatedActionPerformed(evt);
            }
        });
        mnuMainReport.add(mnuRepVoucherActivated);

        jMenuBar1.add(mnuMainReport);

        mnuSetup.setText("Setups");
        mnuSetup.setEnabled(false);

        mnuSetupDealers.setText("Setup Dealers");
        mnuSetupDealers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSetupDealersActionPerformed(evt);
            }
        });
        mnuSetup.add(mnuSetupDealers);

        jMenuBar1.add(mnuSetup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
          setLocationRelativeTo(null);
          //disableComponents();
          //new Login().setVisible(true);
          
          //setExtendedState(MAXIMIZED_BOTH);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void mnuBlackListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBlackListActionPerformed
        try{
          //JOptionPane.showMessageDialog(null,"Hello");
           new CCareGUI().setVisible(true);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_mnuBlackListActionPerformed

    private void mnuDashEnqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDashEnqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuDashEnqActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        
        try{
        
          System.exit(0);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuVCInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVCInfoActionPerformed
        try{
          new VCInfo().setVisible(true);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_mnuVCInfoActionPerformed

    private void mnuESNCleanUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuESNCleanUpActionPerformed
         try{
          new ESNCleaning().setVisible(true);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_mnuESNCleanUpActionPerformed

    private void mnuRUIMCleanUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRUIMCleanUpActionPerformed
       try{
          //JOptionPane.showMessageDialog(null,"Hello");
           new RUIMCleaning().setVisible(true);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_mnuRUIMCleanUpActionPerformed

    private void disableComponents(){
    try{
          //JOptionPane.showMessageDialog(null,"Hello");
          this.mnuVCInfo.setEnabled(false);
          this.mnuVoucherActivation.setEnabled(false);
          this.mnuBlackList.setEnabled(false);
          this.mnuDashEnquiries.setEnabled(false);
          this.mnuESNCleanUp.setEnabled(false);
          this.mnuRUIMCleanUp.setEnabled(false);
          this.mnuEVDOInfo.setEnabled(false);
         
          
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }
    
    public void enableComponents(){
    try{
          //JOptionPane.showMessageDialog(null,"Hello");
          this.mnuVCInfo.setEnabled(true);
          this.mnuVoucherActivation.setEnabled(true);
          this.mnuBlackList.setEnabled(true);
          this.mnuDashEnquiries.setEnabled(true);
          this.mnuESNCleanUp.setEnabled(true);
          this.mnuRUIMCleanUp.setEnabled(true);
          this.mnuEVDOInfo.setEnabled(true);
          
          
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }
    
    
    private void mnuDashEnquiriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDashEnquiriesActionPerformed
        try{
          //JOptionPane.showMessageDialog(null,"Hello");
           new Dash().setVisible(true);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_mnuDashEnquiriesActionPerformed

    private void mnuEVDOInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEVDOInfoActionPerformed
        try{
          //JOptionPane.showMessageDialog(null,"Hello");
           new AccountInfo().setVisible(true);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_mnuEVDOInfoActionPerformed

private void mnuVoucherActivationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVoucherActivationActionPerformed
    try{
          //JOptionPane.showMessageDialog(null,"Hello");
           new VoucherActivation().setVisible(true);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
}//GEN-LAST:event_mnuVoucherActivationActionPerformed

private void mnuMainReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMainReportActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_mnuMainReportActionPerformed

private void mnuRepVoucherActivatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepVoucherActivatedActionPerformed
// TODO add your handling code here:
    try{
          //JOptionPane.showMessageDialog(null,"Hello");
           new ReportData().setVisible(true);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
}//GEN-LAST:event_mnuRepVoucherActivatedActionPerformed

private void mnuSetupDealersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSetupDealersActionPerformed
// TODO add your handling code here:
    try{
          //JOptionPane.showMessageDialog(null,"Hello");
           new SetupDealers().setVisible(true);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
}//GEN-LAST:event_mnuSetupDealersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnuActivations;
    private javax.swing.JMenuItem mnuBlackList;
    private javax.swing.JMenu mnuDashEnq;
    private javax.swing.JMenuItem mnuDashEnquiries;
    private javax.swing.JMenuItem mnuESNCleanUp;
    private javax.swing.JMenuItem mnuEVDOInfo;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuMainReport;
    private javax.swing.JMenuItem mnuRUIMCleanUp;
    private javax.swing.JMenuItem mnuRepVoucherActivated;
    private javax.swing.JMenu mnuSetup;
    private javax.swing.JMenuItem mnuSetupDealers;
    private javax.swing.JMenuItem mnuVCInfo;
    private javax.swing.JMenuItem mnuVoucherActivation;
    // End of variables declaration//GEN-END:variables
}
