/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RUIMCleaning.java
 *
 * Created on Jul 30, 2011, 7:48:39 PM
 */
package my.ccaregui;

/**
 *
 * @author Expresso BRM
 */
import java.sql.*;
import javax.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JDialog;

public class RUIMCleaning extends javax.swing.JFrame {

    String myInput;
    ConnectDB cnn = new ConnectDB();
    Connection con =  cnn.getConnection();
    /** Creates new form RUIMCleaning */
    public RUIMCleaning() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCleanUp = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRUIM = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        lblState = new javax.swing.JLabel();
        lblPUK1 = new javax.swing.JLabel();
        lblPUK2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRuimType = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EXPRESSO TELECOM GH");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCleanUp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCleanUp.setText("Clean Up");
        btnCleanUp.setEnabled(false);
        btnCleanUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanUpActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Enter RUIM");

        txtRUIM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRUIM.setForeground(new java.awt.Color(51, 0, 51));

        btnFind.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        lblState.setBackground(new java.awt.Color(0, 0, 0));
        lblState.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblState.setForeground(new java.awt.Color(102, 0, 0));
        lblState.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblState.setText("RUIM STATE");

        lblPUK1.setBackground(new java.awt.Color(0, 0, 0));
        lblPUK1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPUK1.setForeground(new java.awt.Color(102, 0, 0));
        lblPUK1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblPUK2.setBackground(new java.awt.Color(0, 0, 0));
        lblPUK2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPUK2.setForeground(new java.awt.Color(102, 0, 0));
        lblPUK2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("PUK 1 & 2");

        lblRuimType.setBackground(new java.awt.Color(0, 0, 0));
        lblRuimType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRuimType.setForeground(new java.awt.Color(51, 0, 102));
        lblRuimType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRuimType.setText("RUIM TYPE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRuimType, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPUK2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCleanUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRUIM, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnFind))
                    .addComponent(lblPUK1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRUIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblState)
                .addGap(8, 8, 8)
                .addComponent(lblRuimType)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPUK1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblPUK2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCleanUp)
                    .addComponent(btnClear)
                    .addComponent(btnClose))
                .addGap(5, 5, 5))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 28));
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RUIM CLEAN UP/PUK SEARCH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try{
          setLocationRelativeTo(null);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
       if (con==null){
          ConnectDB cnn = new ConnectDB();
          Connection con =  cnn.getConnection();
       }
    
       try
        { 
         lblPUK1.setText("");
         lblPUK2.setText("");
         txtRUIM.getText().trim();
         if (txtRUIM.getText().length()>=12){
          
          txtRUIM.setText(txtRUIM.getText().trim());
          String userInput ="8923328" +  txtRUIM.getText().substring(txtRUIM.getText().length()-12);
          txtRUIM.setText(userInput);
          
          myInput = txtRUIM.getText().trim();
          
          //lblDisplay.setText(txtMDN.getText().trim());
          Statement s = con.createStatement();
          
           String select ="select t.Device_id, t.State_id, d.puk1, d.puk2, d.RUIM_TYPE " +
                          " from device_t t, device_sim_t d where t.POID_ID0=d.obj_id0 and d.iccid  = '" + myInput + "'";
          
           //String select ="select Device_id, State_id from device_t where POID_ID0 in " +
            //             " (select obj_id0 from device_sim_t where iccid = '" + myInput + "')";
          ResultSet rows;
          rows = s.executeQuery(select);
          
          
              int cnt=0;
              while (rows.next()) {
                  cnt++; 
                  if (String.valueOf(rows.getString(2)).equals("5")){
                        lblState.setText("RUIM is Assigned");
                        btnCleanUp.setEnabled(false);
                        lblPUK1.setText(rows.getString(3));
                        lblPUK2.setText(rows.getString(4));
                        
                        if (String.valueOf(rows.getString(5)).equals("RUIM")){
                            lblRuimType.setText("2G Ruim - Mobile Plan");
                        }
                        else {
                            lblRuimType.setText("3G Ruim - EVDO Plan");
                        }
                        
                     }
                  else if (String.valueOf(rows.getString(2)).equals("2")){
                      
                        lblState.setText("RUIM is New");
                        btnCleanUp.setEnabled(false);
                        lblPUK1.setText(rows.getString(3));
                        lblPUK2.setText(rows.getString(4));
                         if (String.valueOf(rows.getString(5)).equals("RUIM")){
                            lblRuimType.setText("2G Ruim - Mobile Plan");
                        }
                        else {
                            lblRuimType.setText("3G Ruim - EVDO Plan");
                        }
                        
                     }
                   else if (String.valueOf(rows.getString(2)).equals("6")){
                      
                        lblState.setText("RUIM is in Quarantine");
                        btnCleanUp.setEnabled(true);
                        txtRUIM.setEnabled(false);
                        lblPUK1.setText(rows.getString(3));
                        lblPUK2.setText(rows.getString(4));
                         if (String.valueOf(rows.getString(5)).equals("RUIM")){
                            lblRuimType.setText("2G Ruim - Mobile Plan");
                        }
                        else {
                            lblRuimType.setText("3G Ruim - EVDO Plan");
                        }
                     }
                  else if (String.valueOf(rows.getString(2)).equals("3")){
                      
                        lblState.setText("RUIM is in Release State");
                        btnCleanUp.setEnabled(true);
                        txtRUIM.setEnabled(false);
                        lblPUK1.setText(rows.getString(3));
                        lblPUK2.setText(rows.getString(4));
                         if (String.valueOf(rows.getString(5)).equals("RUIM")){
                            lblRuimType.setText("2G Ruim - Mobile Plan");
                        }
                        else {
                            lblRuimType.setText("3G Ruim - EVDO Plan");
                        }
                     }
                  else{
                      
                        lblState.setText("Unknown, Clean up RUIM");
                        btnCleanUp.setEnabled(true);
                        txtRUIM.setEnabled(false);
                        lblPUK1.setText(rows.getString(3));
                        lblPUK2.setText(rows.getString(4));
                         if (String.valueOf(rows.getString(5)).equals("RUIM")){
                            lblRuimType.setText("2G Ruim - Mobile Plan");
                        }
                        else {
                            lblRuimType.setText("3G Ruim - EVDO Plan");
                        }
                     }

              }
             s.close();
             rows.close();
             if (cnt<1){
                  JOptionPane.showMessageDialog(null, "Record not found");
              }
         }
         else{
             JOptionPane.showMessageDialog(null, "Enter Valid RUIM");
             txtRUIM.requestFocus();
         }
        }
        catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnCleanUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanUpActionPerformed
        if (con==null){
            ConnectDB cnn = new ConnectDB();
            Connection con =  cnn.getConnection();
        }
         try{
           //lblDisplay.setText(txtMDN.getText().trim());
          JDialog.setDefaultLookAndFeelDecorated(true);
          int response = JOptionPane.showConfirmDialog(null, "Do you want to continue?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          if (response == JOptionPane.YES_OPTION){
              con.setAutoCommit(false);
              //String myInput = txtMDN.getText().trim();
              Statement s = con.createStatement();  
              s.executeUpdate("update device_t  set STATE_ID = 2 where poid_id0 in " +
                              "(select obj_id0 from device_sim_t where iccid = '" + myInput + "')");

              con.commit();
              ClearData();
              s.close();
             
              JOptionPane.showMessageDialog(null, "RUIM Clean up is Complete");
          
          }
          
         
        }
        catch(SQLException e){
           System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btnCleanUpActionPerformed
  
    //Method to clear data from controls
    private void ClearData(){
        try{
           lblState.setText("RUIM State");
           lblRuimType.setText("RUIM Type");
           txtRUIM.setEnabled(true);
           txtRUIM.setText("");
           lblPUK1.setText("");
           lblPUK2.setText("");
           
           btnCleanUp.setEnabled(false);
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }
    
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        try{
            ClearData();
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
          
        try{
             con.close();
             cnn=null;
             setVisible(false);
             dispose();
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try{
           con.close();
           cnn=null;
        }
        catch(Exception e){
           System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RUIMCleaning().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanUp;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPUK1;
    private javax.swing.JLabel lblPUK2;
    private javax.swing.JLabel lblRuimType;
    private javax.swing.JLabel lblState;
    private javax.swing.JTextField txtRUIM;
    // End of variables declaration//GEN-END:variables
}
